export const citydata = [
  {
    id: 260,
    name: "Yangon (ရန်ကုန်)",
    remark: "Yangon (ရန်ကုန်)",
    townshipCount: 46,
    seqNo: 1,
  },
  {
    id: 104,
    name: "Mandalay (မန္တလေး)",
    remark: "Mandalay (မန္တလေး)",
    townshipCount: 36,
    seqNo: 2,
  },
  {
    id: 144,
    name: "Naypyitaw (Bawga) (နေပြည်တော် (ဘောဂ))",
    remark: "Naypyitaw (Bawga) (နေပြည်တော် (ဘောဂ))",
    townshipCount: 0,
    seqNo: 3,
  },
  {
    id: 145,
    name: "Naypyitaw (Myoma) (နေပြည်တော် (မြို့မ))",
    remark: "Naypyitaw (Myoma) (နေပြည်တော် (မြို့မ))",
    townshipCount: 0,
    seqNo: 5,
  },
  {
    id: 230,
    name: "Taunggyi (တောင်ကြီး)",
    remark: "Taunggyi (တောင်ကြီး)",
    townshipCount: 0,
    seqNo: 6,
  },
  {
    id: 191,
    name: "Pyin Oo Lwin (ပြင်ဦးလွင်)",
    remark: "Pyin Oo Lwin (ပြင်ဦးလွင်)",
    townshipCount: 0,
    seqNo: 7,
  },
  {
    id: 146,
    name: "Naypyitaw (Thapyaygone) (နေပြည်တော် (သပြေကုန်း))",
    remark: "Naypyitaw (Thapyaygone) (နေပြည်တော် (သပြေကုန်း))",
    townshipCount: 0,
    seqNo: 8,
  },
  {
    id: 147,
    name: "Naypyitaw(Toll Gate) (နေပြည်တော်(တိုးဂိတ်))",
    remark: "Naypyitaw(Toll Gate) (နေပြည်တော်(တိုးဂိတ်))",
    townshipCount: 0,
    seqNo: 9,
  },
  {
    id: 7,
    name: "Bagan/Nyaung-U (ပုဂံ/ညောင်ဦး)",
    remark: "Bagan/Nyaung-U (ပုဂံ/ညောင်ဦး)",
    townshipCount: 0,
    seqNo: 10,
  },
  {
    id: 168,
    name: "Pathein (ပုသိမ်)",
    remark: "Pathein (ပုသိမ်)",
    townshipCount: 0,
    seqNo: 11,
  },
  {
    id: 128,
    name: "Myeik (မြိတ်)",
    remark: "Myeik (မြိတ်)",
    townshipCount: 0,
    seqNo: 12,
  },
  {
    id: 132,
    name: "Myitkyina (မြစ်ကြီးနား)",
    remark: "Myitkyina (မြစ်ကြီးနား)",
    townshipCount: 0,
    seqNo: 13,
  },
  {
    id: 96,
    name: "Loikaw (လွိုင်ကော်)",
    remark: "Loikaw (လွိုင်ကော်)",
    townshipCount: 0,
    seqNo: 14,
  },
  {
    id: 33,
    name: "Hpa-An (ဘားအံ)",
    remark: "Hpa-An (ဘားအံ)",
    townshipCount: 0,
    seqNo: 15,
  },
  {
    id: 27,
    name: "Hakha (ဟားခါး)",
    remark: "Hakha (ဟားခါး)",
    townshipCount: 0,
    seqNo: 16,
  },
  {
    id: 197,
    name: "Sagaing (စစ်ကိုင်း)",
    remark: "Sagaing (စစ်ကိုင်း)",
    townshipCount: 0,
    seqNo: 17,
  },
  {
    id: 101,
    name: "Magway (မကွေး)",
    remark: "Magway (မကွေး)",
    townshipCount: 0,
    seqNo: 18,
  },
  {
    id: 108,
    name: "Mawlamyine (မော်လမြိုင်)",
    remark: "Mawlamyine (မော်လမြိုင်)",
    townshipCount: 0,
    seqNo: 19,
  },
  {
    id: 221,
    name: "Sittwe (စစ်တွေ)",
    remark: "Sittwe (စစ်တွေ)",
    townshipCount: 0,
    seqNo: 20,
  },
  {
    id: 279,
    name: "Kyaing Tong (ကျိုင်းတုံ)",
    remark: "Kyaing Tong (ကျိုင်းတုံ)",
    townshipCount: 0,
    seqNo: 21,
  },
  {
    id: 1,
    name: "39 Phayagyi (၃၉ဘုရားကြီး)",
    remark: "39 Phayagyi (၃၉ဘုရားကြီး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 2,
    name: "Ahtet Min Hla (အထက် မင်းလှ)",
    remark: "Ahtet Min Hla (အထက် မင်းလှ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 3,
    name: "Ann (အမ်း)",
    remark: "Ann (အမ်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 299,
    name: "Atote(အသုတ်)",
    remark: "Atote(အသုတ်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 4,
    name: "AungLan (အောင်လံ)",
    remark: "AungLan (အောင်လံ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 5,
    name: "Aungpan (အောင်ပန်း)",
    remark: "Aungpan (အောင်ပန်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 6,
    name: "Ayadaw (အရာတော်)",
    remark: "Ayadaw (အရာတော်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 8,
    name: "Bago (ပဲခူး)",
    remark: "Bago (ပဲခူး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 9,
    name: "Bahin (ဗဟင်း)",
    remark: "Bahin (ဗဟင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 10,
    name: "Bhamo (ဗန်းမော်)",
    remark: "Bhamo (ဗန်းမော်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 11,
    name: "Bilin (ဘီးလင်း)",
    remark: "Bilin (ဘီးလင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 291,
    name: "Bogale(ဘိုကလေး)",
    remark: "Bogale(ဘိုကလေး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 12,
    name: "Bokpyin (ဘုတ်ပြင်း)",
    remark: "Bokpyin (ဘုတ်ပြင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 13,
    name: "Budalin (ဘုတလင်)",
    remark: "Budalin (ဘုတလင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 281,
    name: "Buthidaung (ဘူးသီးတောင်)",
    remark: "Buthidaung (ဘူးသီးတောင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 14,
    name: "Chauk (ချောက်)",
    remark: "Chauk (ချောက်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 15,
    name: "ChaungU (ချောင်းဦး)",
    remark: "ChaungU (ချောင်းဦး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 16,
    name: "Chaungzon (ချောင်းဆုံ)",
    remark: "Chaungzon (ချောင်းဆုံ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 17,
    name: "Daik-U (ဒိုက်ဦး)",
    remark: "Daik-U (ဒိုက်ဦး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 18,
    name: "Danai (တနိုင်း)",
    remark: "Danai (တနိုင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 19,
    name: "Danubyu (ဓနုဖြူ)",
    remark: "Danubyu (ဓနုဖြူ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 20,
    name: "Dawei (ထားဝယ်)",
    remark: "Dawei (ထားဝယ်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 292,
    name: "Dedaye(ဒေးဒရဲ)",
    remark: "Dedaye(ဒေးဒရဲ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 21,
    name: "Demoso (ဒီမောဆို)",
    remark: "Demoso (ဒီမောဆို)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 22,
    name: "Eaindu (အိန္ဒု)",
    remark: "Eaindu (အိန္ဒု)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 295,
    name: "Einme(အိမ်မဲ)",
    remark: "Einme(အိမ်မဲ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 23,
    name: "Gangaw (ဂန့်ဂေါ)",
    remark: "Gangaw (ဂန့်ဂေါ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 24,
    name: "Gwa (ဂွ)",
    remark: "Gwa (ဂွ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 25,
    name: "Gway Gone (ဂွေးကုန်း)",
    remark: "Gway Gone (ဂွေးကုန်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 26,
    name: "Gyobingauk (ကြို့ပင်ကောက်)",
    remark: "Gyobingauk (ကြို့ပင်ကောက်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 28,
    name: "HeHoe (ဟဲဟိုး)",
    remark: "HeHoe (ဟဲဟိုး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 29,
    name: "Hinthada (ဟင်္သာတ)",
    remark: "Hinthada (ဟင်္သာတ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 30,
    name: "Hopin (ဟိုပင်)",
    remark: "Hopin (ဟိုပင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 31,
    name: "Hopong (ဟိုပုံး)",
    remark: "Hopong (ဟိုပုံး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 32,
    name: "Hpa Do (ဖဒို)",
    remark: "Hpa Do (ဖဒို)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 34,
    name: "Hpakan (ဖားကန့်)",
    remark: "Hpakan (ဖားကန့်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 35,
    name: "Hpapun (ဖာပွန်)",
    remark: "Hpapun (ဖာပွန်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 36,
    name: "Hpayargyi (ဘုရားကြီး)",
    remark: "Hpayargyi (ဘုရားကြီး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 37,
    name: "Hseni (သိန္နီ)",
    remark: "Hseni (သိန္နီ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 38,
    name: "Hsipaw (သီပေါ)",
    remark: "Hsipaw (သီပေါ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 39,
    name: "Htonebo (ထုံးဘို)",
    remark: "Htonebo (ထုံးဘို)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 40,
    name: "Hway Khar (ဝှေ့ခါ)",
    remark: "Hway Khar (ဝှေ့ခါ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 41,
    name: "InDaw (အင်းတော်)",
    remark: "InDaw (အင်းတော်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 42,
    name: "Inle (အင်းလေး)",
    remark: "Inle (အင်းလေး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 43,
    name: "InnMa (အင်းမ)",
    remark: "InnMa (အင်းမ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 44,
    name: "Ka Nyut Kwin (ကညွတ်ကွင်း)",
    remark: "Ka Nyut Kwin (ကညွတ်ကွင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 45,
    name: "Kabyu (ကမ်းဗြူး)",
    remark: "Kabyu (ကမ်းဗြူး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 46,
    name: "Kaduma (ကံထူးမ)",
    remark: "Kaduma (ကံထူးမ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 47,
    name: "Kaing Taw Ma (ကိုင်းတောမ)",
    remark: "Kaing Taw Ma (ကိုင်းတောမ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 48,
    name: "Kalar Pyin (ကုလားပြင်)",
    remark: "Kalar Pyin (ကုလားပြင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 49,
    name: "Kalaw (ကလော)",
    remark: "Kalaw (ကလော)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 50,
    name: "Kale (ကလေး)",
    remark: "Kale (ကလေး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 51,
    name: "Kamarmaung (ကမမောင်း)",
    remark: "Kamarmaung (ကမမောင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 52,
    name: "Kamma (ကမ္မ)",
    remark: "Kamma (ကမ္မ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 54,
    name: "Kanbalu (ကန့်ဘလူ)",
    remark: "Kanbalu (ကန့်ဘလူ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 55,
    name: "Kanbya (ကန်ပြား)",
    remark: "Kanbya (ကန်ပြား)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 53,
    name: "KanMa (ကံမ)",
    remark: "KanMa (ကံမ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 56,
    name: "Kanpetlet (ကန်ပက်လက်)",
    remark: "Kanpetlet (ကန်ပက်လက်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 57,
    name: "Kar Boe (ကာဘိုး)",
    remark: "Kar Boe (ကာဘိုး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 58,
    name: "Karbo (ကာဘိုး-ဇီးကုန်း)",
    remark: "Karbo (ကာဘိုး-ဇီးကုန်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 59,
    name: "Katha (ကသာ)",
    remark: "Katha (ကသာ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 60,
    name: "Kawkareik (ကော့ကရိတ်)",
    remark: "Kawkareik (ကော့ကရိတ်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 61,
    name: "Kawthaung (ကော့သောင်း)",
    remark: "Kawthaung (ကော့သောင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 62,
    name: "Kazukaing (ကဇူးကိုင်း)",
    remark: "Kazukaing (ကဇူးကိုင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 63,
    name: "Khin-U (ခင်ဦး)",
    remark: "Khin-U (ခင်ဦး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 64,
    name: "Kon Zaung (ကုန်းဇောင်း)",
    remark: "Kon Zaung (ကုန်းဇောင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 65,
    name: "Kume (ကူမဲ)",
    remark: "Kume (ကူမဲ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 66,
    name: "Kutkai (ကွတ်ခိုင်)",
    remark: "Kutkai (ကွတ်ခိုင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 67,
    name: "Kyaikkami (ကျိုက်ခမီ)",
    remark: "Kyaikkami (ကျိုက်ခမီ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 68,
    name: "Kyaiklat (ကျိုက်လတ်)",
    remark: "Kyaiklat (ကျိုက်လတ်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 69,
    name: "Kyaikto (ကျိုက်ထို)",
    remark: "Kyaikto (ကျိုက်ထို)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 70,
    name: "Kyangin (ကြံခင်း)",
    remark: "Kyangin (ကြံခင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 71,
    name: "Kyar Kan (ကြာကန်)",
    remark: "Kyar Kan (ကြာကန်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 72,
    name: "Kyauk Gyi (ကျောက်ကြီး)",
    remark: "Kyauk Gyi (ကျောက်ကြီး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 73,
    name: "Kyauk Tan (ကျောက်တန်း)",
    remark: "Kyauk Tan (ကျောက်တန်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 74,
    name: "Kyaukkyi (ကျောက်ကြီး)",
    remark: "Kyaukkyi (ကျောက်ကြီး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 75,
    name: "Kyaukme (ကျောက်မဲ)",
    remark: "Kyaukme (ကျောက်မဲ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 76,
    name: "Kyaukpadaung (ကျောက်ပန်းတောင်း)",
    remark: "Kyaukpadaung (ကျောက်ပန်းတောင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 77,
    name: "Kyaukphyu (ကျောက်ဖြူ)",
    remark: "Kyaukphyu (ကျောက်ဖြူ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 78,
    name: "Kyaukse (ကျောက်ဆည်)",
    remark: "Kyaukse (ကျောက်ဆည်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 79,
    name: "Kyauktaga (ကျောက်တံခါး)",
    remark: "Kyauktaga (ကျောက်တံခါး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 80,
    name: "Kyauktaw (ကျောက်တော်)",
    remark: "Kyauktaw (ကျောက်တော်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 81,
    name: "Kyaukyit (ကျောက်ရစ်)",
    remark: "Kyaukyit (ကျောက်ရစ်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 82,
    name: "Kyaung Taw Yar (ကျောင်းတော်ရာ)",
    remark: "Kyaung Taw Yar (ကျောင်းတော်ရာ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 83,
    name: "Kyaw (ကျော)",
    remark: "Kyaw (ကျော)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 84,
    name: "Kyeintali (ကျိန္တလီ)",
    remark: "Kyeintali (ကျိန္တလီ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 85,
    name: "Kyi Tauk Pauk (ကျဉ်တောက်ပေါက်)",
    remark: "Kyi Tauk Pauk (ကျဉ်တောက်ပေါက်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 86,
    name: "Kyondoe (ကျုံဒိုး)",
    remark: "Kyondoe (ကျုံဒိုး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 296,
    name: "Kyonpyaw(ကျုံပျော်)",
    remark: "Kyonpyaw(ကျုံပျော်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 87,
    name: "Kyun Hla (ကျွန်းလှ)",
    remark: "Kyun Hla (ကျွန်းလှ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 88,
    name: "Kyunchaung (ကျွန်းချောင်း)",
    remark: "Kyunchaung (ကျွန်းချောင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 89,
    name: "Lashio (လားရှိုး)",
    remark: "Lashio (လားရှိုး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 90,
    name: "Lat Pan Hla (လက်ပံလှ)",
    remark: "Lat Pan Hla (လက်ပံလှ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 91,
    name: "Lat Yin Ma (လက်ယက်မ)",
    remark: "Lat Yin Ma (လက်ယက်မ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 92,
    name: "Lawksawk (ရပ်စောက်)",
    remark: "Lawksawk (ရပ်စောက်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 93,
    name: "Lay Tine Sin (လေးတိုင်စင်)",
    remark: "Lay Tine Sin (လေးတိုင်စင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 94,
    name: "Letpadan (လက်ပံတန်း)",
    remark: "Letpadan (လက်ပံတန်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 95,
    name: "Lewe (လယ်ဝေး)",
    remark: "Lewe (လယ်ဝေး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 97,
    name: "Loilem (လွိုင်လင်)",
    remark: "Loilem (လွိုင်လင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 98,
    name: "Lonkin (လုံးခင်း)",
    remark: "Lonkin (လုံးခင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 100,
    name: "Madaya (မတ္တရာ)",
    remark: "Madaya (မတ္တရာ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 99,
    name: "Ma-ei (မအီ)",
    remark: "Ma-ei (မအီ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 102,
    name: "Mahlaing (မလှိုင်)",
    remark: "Mahlaing (မလှိုင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 103,
    name: "Malun (မလွန်)",
    remark: "Malun (မလွန်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 105,
    name: "Maubin (မအူပင်)",
    remark: "Maubin (မအူပင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 283,
    name: "Maungdaw (မောင်တော)",
    remark: "Maungdaw (မောင်တော)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 106,
    name: "Maw Hun (မော်ဟန်)",
    remark: "Maw Hun (မော်ဟန်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 107,
    name: "Maw Luu (မော်လူး)",
    remark: "Maw Luu (မော်လူး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 293,
    name: "Mawgyun(မော်ကျွန်း)",
    remark: "Mawgyun(မော်ကျွန်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 109,
    name: "Meiktila (မိတ္ထီလာ)",
    remark: "Meiktila (မိတ္ထီလာ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 110,
    name: "Migyaungye (မိကျောင်းရဲ)",
    remark: "Migyaungye (မိကျောင်းရဲ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 112,
    name: "Minbu (မင်းဘူး)",
    remark: "Minbu (မင်းဘူး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 111,
    name: "MinBya (မင်းပြား)",
    remark: "MinBya (မင်းပြား)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 113,
    name: "Moebyel (မိုးဗြဲ)",
    remark: "Moebyel (မိုးဗြဲ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 114,
    name: "Mogaung (မိုးကောင်း)",
    remark: "Mogaung (မိုးကောင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 115,
    name: "Mogok (မိုးကုတ်)",
    remark: "Mogok (မိုးကုတ်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 116,
    name: "Mohnyin (မိုးညှင်း)",
    remark: "Mohnyin (မိုးညှင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 117,
    name: "Mon (မုန်း)",
    remark: "Mon (မုန်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 118,
    name: "Mong Pawn (မိုင်းပွန်)",
    remark: "Mong Pawn (မိုင်းပွန်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 119,
    name: "Monywa (မုံရွာ)",
    remark: "Monywa (မုံရွာ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 120,
    name: "Mrauk-U (မြောက်ဦး)",
    remark: "Mrauk-U (မြောက်ဦး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 121,
    name: "Mudon (မုဒုံ)",
    remark: "Mudon (မုဒုံ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 122,
    name: "Mukangyi (မူးကမ်းကြီး)",
    remark: "Mukangyi (မူးကမ်းကြီး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 282,
    name: "Munaung (မာန်အောင်)",
    remark: "Munaung (မာန်အောင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 123,
    name: "Muse (မူဆယ်)",
    remark: "Muse (မူဆယ်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 124,
    name: "Myaing (မြိုင်)",
    remark: "Myaing (မြိုင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 125,
    name: "Myanaung (မြန်အောင်)",
    remark: "Myanaung (မြန်အောင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 126,
    name: "Myaungmya (မြောင်းမြ)",
    remark: "Myaungmya (မြောင်းမြ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 127,
    name: "Myawaddy (မြဝတီ)",
    remark: "Myawaddy (မြဝတီ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 284,
    name: "Myebon (မြေပုံ)",
    remark: "Myebon (မြေပုံ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 129,
    name: "Myin Kun (မြင်ကွန်း)",
    remark: "Myin Kun (မြင်ကွန်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 130,
    name: "Myingyan (မြင်းခြံ)",
    remark: "Myingyan (မြင်းခြံ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 131,
    name: "Myitchay (မြစ်ခြေ)",
    remark: "Myitchay (မြစ်ခြေ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 133,
    name: "Myittha (မြစ်သား)",
    remark: "Myittha (မြစ်သား)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 134,
    name: "Myo Chaung (မြို့ချောင်း)",
    remark: "Myo Chaung (မြို့ချောင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 135,
    name: "Myothit (မြို့သစ်)",
    remark: "Myothit (မြို့သစ်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 136,
    name: "Nam Hpat Kar (နမ့်ဖတ်ကာ)",
    remark: "Nam Hpat Kar (နမ့်ဖတ်ကာ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 137,
    name: "Namsang (နမ့်စန်)",
    remark: "Namsang (နမ့်စန်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 138,
    name: "Nanmati (နမ္မတီး)",
    remark: "Nanmati (နမ္မတီး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 139,
    name: "Natmauk (နတ်မောက်)",
    remark: "Natmauk (နတ်မောက်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 140,
    name: "Natogyi (နွားထိုးကြီး)",
    remark: "Natogyi (နွားထိုးကြီး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 141,
    name: "Nattalin (နတ္တလင်း)",
    remark: "Nattalin (နတ္တလင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 142,
    name: "Natthankwin (နတ်သံကွင်း)",
    remark: "Natthankwin (နတ်သံကွင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 143,
    name: "Nawnghkio (နောင်ချို)",
    remark: "Nawnghkio (နောင်ချို)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 148,
    name: "Ngapali (ငပလီ)",
    remark: "Ngapali (ငပလီ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 149,
    name: "Ngar O (ငါးအိုး)",
    remark: "Ngar O (ငါးအိုး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 298,
    name: "Ngatai Chaung(ငါးသိုက်ချောင်း)",
    remark: "Ngatai Chaung(ငါးသိုက်ချောင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 150,
    name: "Ngathayauk (ငါ့သရောက်)",
    remark: "Ngathayauk (ငါ့သရောက်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 151,
    name: "Nyaung Chay Htauk (ညောင်ခြေထောက်)",
    remark: "Nyaung Chay Htauk (ညောင်ခြေထောက်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 152,
    name: "Nyaung Kone (ညောင်ကုန်း)",
    remark: "Nyaung Kone (ညောင်ကုန်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 153,
    name: "Nyaung Lay Pin (ညောင်လေးပင်)",
    remark: "Nyaung Lay Pin (ညောင်လေးပင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 154,
    name: "Nyaung Shwe(Inle) (ညောင်ရွှေ(အင်းလေး))",
    remark: "Nyaung Shwe(Inle) (ညောင်ရွှေ(အင်းလေး))",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 156,
    name: "Nyaungdon (ညောင်တုန်း)",
    remark: "Nyaungdon (ညောင်တုန်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 155,
    name: "NyaungPin (ညောင်ပင်)",
    remark: "NyaungPin (ညောင်ပင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 157,
    name: "Oak Pho (အုတ်ဖို)",
    remark: "Oak Pho (အုတ်ဖို)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 158,
    name: "Oke Shit Pin (ဥသျှစ်ပင်)",
    remark: "Oke Shit Pin (ဥသျှစ်ပင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 159,
    name: "Oktwin (အုတ်တွင်း)",
    remark: "Oktwin (အုတ်တွင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 160,
    name: "Padaung (ပန်းတောင်း)",
    remark: "Padaung (ပန်းတောင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 161,
    name: "Padein (ပဒါန်း)",
    remark: "Padein (ပဒါန်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 162,
    name: "Padigon (ပုတီးကုန်း)",
    remark: "Padigon (ပုတီးကုန်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 163,
    name: "Pakokku (ပခုက္ကူ)",
    remark: "Pakokku (ပခုက္ကူ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 164,
    name: "Pala (ပလ)",
    remark: "Pala (ပလ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 165,
    name: "Palauk (ပလောက်)",
    remark: "Palauk (ပလောက်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 166,
    name: "Palaw (ပုလော)",
    remark: "Palaw (ပုလော)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 167,
    name: "Pale (ပုလဲ)",
    remark: "Pale (ပုလဲ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 294,
    name: "Pantanaw(ပန်းတနော်)",
    remark: "Pantanaw(ပန်းတနော်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 169,
    name: "Pauk (ပေါက်)",
    remark: "Pauk (ပေါက်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 170,
    name: "Paukkhaung (ပေါက်ခေါင်း)",
    remark: "Paukkhaung (ပေါက်ခေါင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 171,
    name: "Pauktaw (ပေါက်တော)",
    remark: "Pauktaw (ပေါက်တော)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 172,
    name: "Paung (ပေါင်)",
    remark: "Paung (ပေါင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 173,
    name: "Paungdale (ပေါင်းတလည်)",
    remark: "Paungdale (ပေါင်းတလည်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 174,
    name: "Paungde (ပေါင်းတည်)",
    remark: "Paungde (ပေါင်းတည်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 175,
    name: "Pay Pin Tike (ပေပင်တိုက်)",
    remark: "Pay Pin Tike (ပေပင်တိုက်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 176,
    name: "Payangazu (ဘုရားငါးဆူ)",
    remark: "Payangazu (ဘုရားငါးဆူ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 177,
    name: "Pekon (ဖယ်ခုံ)",
    remark: "Pekon (ဖယ်ခုံ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 178,
    name: "Penwegon (ပဲနွယ်ကုန်း)",
    remark: "Penwegon (ပဲနွယ်ကုန်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 179,
    name: "Phar Auk (ဖားအောက်)",
    remark: "Phar Auk (ဖားအောက်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 180,
    name: "Phyu (ဖြူး)",
    remark: "Phyu (ဖြူး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 181,
    name: "Pinbaw (ပင်းဘော)",
    remark: "Pinbaw (ပင်းဘော)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 182,
    name: "Pindaya (ပင်းတယ)",
    remark: "Pindaya (ပင်းတယ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 183,
    name: "Pinlaung (ပင်လောင်း)",
    remark: "Pinlaung (ပင်လောင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 184,
    name: "Pinlon (ပင်လုံ)",
    remark: "Pinlon (ပင်လုံ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 185,
    name: "Ponnagyun (ပုဏ္ဏားကျွန်း)",
    remark: "Ponnagyun (ပုဏ္ဏားကျွန်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 186,
    name: "Popa (ပုပ္ပါး)",
    remark: "Popa (ပုပ္ပါး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 187,
    name: "Pwintbyu (ပွင့်ဖြူ)",
    remark: "Pwintbyu (ပွင့်ဖြူ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 188,
    name: "Pyapon (ဖျာပုံ)",
    remark: "Pyapon (ဖျာပုံ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 189,
    name: "Pyawbwe (ပျော်ဘွယ်)",
    remark: "Pyawbwe (ပျော်ဘွယ်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 190,
    name: "Pyay (ပြည်)",
    remark: "Pyay (ပြည်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 300,
    name: "Pyinmanar(ပျင်းမနား)",
    remark: "Pyinmanar(ပျင်းမနား)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 192,
    name: "Pyinsi (ပြင်စီ)",
    remark: "Pyinsi (ပြင်စီ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 193,
    name: "Pyinyaung (ပြည်ညောင်)",
    remark: "Pyinyaung (ပြည်ညောင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 194,
    name: "Pyuntasa (ပြွန်တန်ဆာ)",
    remark: "Pyuntasa (ပြွန်တန်ဆာ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 285,
    name: "Rathedaung (ရသေ့တောင်)",
    remark: "Rathedaung (ရသေ့တောင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 195,
    name: "Sa Bai Nant Thar (စံပါယ်နံ့သာ)",
    remark: "Sa Bai Nant Thar (စံပါယ်နံ့သာ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 196,
    name: "Sadaung (ဆားတောင်)",
    remark: "Sadaung (ဆားတောင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 198,
    name: "Sahmaw (ဆားမှော်)",
    remark: "Sahmaw (ဆားမှော်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 199,
    name: "Saing Gaung (စိုင်ကောင်း)",
    remark: "Saing Gaung (စိုင်ကောင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 200,
    name: "Saing Pyin (စိုင်ပြင်)",
    remark: "Saing Pyin (စိုင်ပြင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 201,
    name: "Saing Taung (ဆိုင်းတောင်)",
    remark: "Saing Taung (ဆိုင်းတောင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 202,
    name: "Salin (စလင်း)",
    remark: "Salin (စလင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 203,
    name: "Sane (စနဲ)",
    remark: "Sane (စနဲ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 204,
    name: "Sat Thwar (ဆတ်သွား)",
    remark: "Sat Thwar (ဆတ်သွား)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 205,
    name: "Sate Htain (စိတ္ထိန်း)",
    remark: "Sate Htain (စိတ္ထိန်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 206,
    name: "Satthwa (ဆပ်သွား)",
    remark: "Satthwa (ဆပ်သွား)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 207,
    name: "Saw (ဆော)",
    remark: "Saw (ဆော)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 208,
    name: "Seikphyu (ဆိပ်ဖြူ)",
    remark: "Seikphyu (ဆိပ်ဖြူ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 209,
    name: "Shwe Ku (ရွှေကူ)",
    remark: "Shwe Ku (ရွှေကူ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 210,
    name: "Shwe Nyaung (ရွှေညောင်)",
    remark: "Shwe Nyaung (ရွှေညောင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 211,
    name: "Shwe Nyaung(Inle) (ရွှေညောင်(အင်းလေး))",
    remark: "Shwe Nyaung(Inle) (ရွှေညောင်(အင်းလေး))",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 212,
    name: "Shwe Set Taw (ရွှေစက်တော်)",
    remark: "Shwe Set Taw (ရွှေစက်တော်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 213,
    name: "Shwebo (ရွှေဘို)",
    remark: "Shwebo (ရွှေဘို)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 214,
    name: "Shwedaung (ရွှေတောင်)",
    remark: "Shwedaung (ရွှေတောင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 215,
    name: "Shwehlae (ရွှေလှေ)",
    remark: "Shwehlae (ရွှေလှေ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 216,
    name: "Si Mee Khon (ဆီမီးခုံ)",
    remark: "Si Mee Khon (ဆီမီးခုံ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 217,
    name: "Si Sone Gone (ဆီဆုံကုန်း)",
    remark: "Si Sone Gone (ဆီဆုံကုန်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 218,
    name: "Sin Hpyu Kyun (ဆင်ဖြူကျွန်း)",
    remark: "Sin Hpyu Kyun (ဆင်ဖြူကျွန်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 219,
    name: "Sinde (ဆင်တဲ)",
    remark: "Sinde (ဆင်တဲ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 220,
    name: "Sinphyushin (ဆင်ဖြူရှင်)",
    remark: "Sinphyushin (ဆင်ဖြူရှင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 222,
    name: "Swar (ဆွာ)",
    remark: "Swar (ဆွာ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 223,
    name: "Ta Nyaung (တညောင်)",
    remark: "Ta Nyaung (တညောင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 224,
    name: "Tabayin (ဒီပဲယင်း)",
    remark: "Tabayin (ဒီပဲယင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 280,
    name: "Tachileik (တာချီလိတ်)",
    remark: "Tachileik (တာချီလိတ်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 225,
    name: "Takon (တပ်ကုန်း)",
    remark: "Takon (တပ်ကုန်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 226,
    name: "Tamu (တမူး)",
    remark: "Tamu (တမူး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 227,
    name: "Tanintharyi (တနင်္သာရီ)",
    remark: "Tanintharyi (တနင်္သာရီ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 228,
    name: "Tatkon (တပ်ကုန်း)",
    remark: "Tatkon (တပ်ကုန်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 229,
    name: "Taungdwingyi (တောင်တွင်းကြီး)",
    remark: "Taungdwingyi (တောင်တွင်းကြီး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 231,
    name: "Taungoo (တောင်ငူ)",
    remark: "Taungoo (တောင်ငူ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 232,
    name: "Taungtha (တောင်သာ)",
    remark: "Taungtha (တောင်သာ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 233,
    name: "Taw Kyel Inn (တောကျွဲအင်း)",
    remark: "Taw Kyel Inn (တောကျွဲအင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 234,
    name: "Taze (တန့်ဆည်)",
    remark: "Taze (တန့်ဆည်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 235,
    name: "Tha Mone Kone (သမုန်းကုန်း)",
    remark: "Tha Mone Kone (သမုန်းကုန်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 236,
    name: "Tha Phan Chaung (သဖန်းချောင်း)",
    remark: "Tha Phan Chaung (သဖန်းချောင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 237,
    name: "Tha Phay Wa (သပြေဝ)",
    remark: "Tha Phay Wa (သပြေဝ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 238,
    name: "Thanbyuzayat (သံဖြူဇရပ်)",
    remark: "Thanbyuzayat (သံဖြူဇရပ်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 239,
    name: "Thandwe (သံတွဲ)",
    remark: "Thandwe (သံတွဲ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 240,
    name: "Thar Ma Nya (သာမည)",
    remark: "Thar Ma Nya (သာမည)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 241,
    name: "Thar Wut Hti (သာဝတ်ထိ)",
    remark: "Thar Wut Hti (သာဝတ်ထိ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 301,
    name: "Tharyarwady(သာယာဝတီ)",
    remark: "Tharyarwady(သာယာဝတီ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 242,
    name: "Thaton (သထုံ)",
    remark: "Thaton (သထုံ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 243,
    name: "Thayet (သရက်)",
    remark: "Thayet (သရက်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 244,
    name: "Thazi (သာစည်)",
    remark: "Thazi (သာစည်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 245,
    name: "Thegon (သဲကုန်း)",
    remark: "Thegon (သဲကုန်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 246,
    name: "Thit Yar Kout (သစ်ရာကောက်)",
    remark: "Thit Yar Kout (သစ်ရာကောက်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 247,
    name: "Tigyaing (ထီးချိုင့်)",
    remark: "Tigyaing (ထီးချိုင့်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 248,
    name: "Tike Chaung (သိုက်ချောင်း)",
    remark: "Tike Chaung (သိုက်ချောင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 249,
    name: "Tilin (ထီးလင်း)",
    remark: "Tilin (ထီးလင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 250,
    name: "Toungup (တောင်ကုတ်)",
    remark: "Toungup (တောင်ကုတ်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 286,
    name: "Ushikpin (ဥသျှစ်ပင်)",
    remark: "Ushikpin (ဥသျှစ်ပင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 251,
    name: "Wathtikan (ဝက်ထီးကန်)",
    remark: "Wathtikan (ဝက်ထီးကန်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 252,
    name: "Waw (ဝေါ)",
    remark: "Waw (ဝေါ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 253,
    name: "Wea Laung (ဝဲလောင်)",
    remark: "Wea Laung (ဝဲလောင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 254,
    name: "Wetpoat (ဝတ်ပုတ်)",
    remark: "Wetpoat (ဝတ်ပုတ်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 255,
    name: "Wundwin (ဝမ်းတွင်း)",
    remark: "Wundwin (ဝမ်းတွင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 256,
    name: "Yae Nan Ma (ရေနံမ)",
    remark: "Yae Nan Ma (ရေနံမ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 257,
    name: "Yae Ni (ရေနီ)",
    remark: "Yae Ni (ရေနီ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 258,
    name: "Yamethin (ရမည်းသင်း)",
    remark: "Yamethin (ရမည်းသင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 259,
    name: "Yanbye (ရမ်းဗြဲ)",
    remark: "Yanbye (ရမ်းဗြဲ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 261,
    name: "Ye (ရေး)",
    remark: "Ye (ရေး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 262,
    name: "Ye Nan Thar (ရေနံ့သာ)",
    remark: "Ye Nan Thar (ရေနံ့သာ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 264,
    name: "Yebyar (ရေပြာ)",
    remark: "Yebyar (ရေပြာ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 265,
    name: "Yedashe (ရေတာရှည်)",
    remark: "Yedashe (ရေတာရှည်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 297,
    name: "Yegyi(ရေကြည်)",
    remark: "Yegyi(ရေကြည်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 266,
    name: "Yenangyaung (ရေနံချောင်း)",
    remark: "Yenangyaung (ရေနံချောင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 267,
    name: "Yesagyo (ရေစကြို)",
    remark: "Yesagyo (ရေစကြို)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 263,
    name: "YeU (ရေဦး)",
    remark: "YeU (ရေဦး)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 268,
    name: "Yin Mar Bin (ယင်းမာပင်)",
    remark: "Yin Mar Bin (ယင်းမာပင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 269,
    name: "Ywar Mon (ရွာမွန်)",
    remark: "Ywar Mon (ရွာမွန်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 270,
    name: "Ywarthit (ရွာသစ်)",
    remark: "Ywarthit (ရွာသစ်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 271,
    name: "Za Ya Wa Di (ဇေယျဝတီ)",
    remark: "Za Ya Wa Di (ဇေယျဝတီ)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 272,
    name: "Zalun (ဇလွန်)",
    remark: "Zalun (ဇလွန်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 273,
    name: "Zayat Kwin (ဇရပ်ကွင်း)",
    remark: "Zayat Kwin (ဇရပ်ကွင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 274,
    name: "Zi Phyu Pin (ဇီးဖြူပင်)",
    remark: "Zi Phyu Pin (ဇီးဖြူပင်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 275,
    name: "Zigon (ဇီးကုန်း)",
    remark: "Zigon (ဇီးကုန်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 276,
    name: "Zigon(Kanbalu) (ဇီးကုန်း)",
    remark: "Zigon(Kanbalu) (ဇီးကုန်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 277,
    name: "Zin Chaung (ဇင်ချောင်း)",
    remark: "Zin Chaung (ဇင်ချောင်း)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 278,
    name: "Zin Kyaik (ဇင်းကျိုက်)",
    remark: "Zin Kyaik (ဇင်းကျိုက်)",
    townshipCount: 0,
    seqNo: 0,
  },
  {
    id: 290,
    name: "Other",
    remark: "Other",
    townshipCount: 0,
    seqNo: 0,
  },
];
