export const townShipData = [
  {
    id: 27,
    name: "Ahlone (အလုံ)",
    description: "Ahlone (အလုံ)",
    cityId: 260,
  },
  {
    id: 28,
    name: "Bahan (ဗဟန်း)",
    description: "Bahan (ဗဟန်း)",
    cityId: 260,
  },
  {
    id: 29,
    name: "Botahtaung(ဗိုလ်တထောင်)",
    description: "Botahtaung(ဗိုလ်တထောင်)",
    cityId: 260,
  },
  {
    id: 30,
    name: "Cocokyun (ကိုကိုးကျွန်း)",
    description: "Cocokyun (ကိုကိုးကျွန်း)",
    cityId: 260,
  },
  {
    id: 31,
    name: "Dagon Seikkan (ဒဂုံဆိပ်ကမ်း)",
    description: "Dagon Seikkan (ဒဂုံဆိပ်ကမ်း)",
    cityId: 260,
  },
  {
    id: 32,
    name: "Dagon (ဒဂုံ)",
    description: "Dagon (ဒဂုံ)",
    cityId: 260,
  },
  {
    id: 33,
    name: "Dala (ဒလ)",
    description: "Dala (ဒလ)",
    cityId: 260,
  },
  {
    id: 34,
    name: "Dawbon (ဒေါပုံ)",
    description: "Dawbon (ဒေါပုံ)",
    cityId: 260,
  },
  {
    id: 35,
    name: "East Dagon (ဒဂုံမြို့သစ် (အရှေ့ပိုင်း))",
    description: "East Dagon (ဒဂုံမြို့သစ် (အရှေ့ပိုင်း))",
    cityId: 260,
  },
  {
    id: 36,
    name: "Hlaing (လှိုင်)",
    description: "Hlaing (လှိုင်)",
    cityId: 260,
  },
  {
    id: 37,
    name: "Hlaingthaya (လှိုင်သာယာ)",
    description: "Hlaingthaya (လှိုင်သာယာ)",
    cityId: 260,
  },
  {
    id: 38,
    name: "Insein (အင်းစိန်)",
    description: "Insein (အင်းစိန်)",
    cityId: 260,
  },
  {
    id: 39,
    name: "Kamayut (ကမာရွတ်)",
    description: "Kamayut (ကမာရွတ်)",
    cityId: 260,
  },
  {
    id: 40,
    name: "Kyauktada (ကျောက်တံတား)",
    description: "Kyauktada (ကျောက်တံတား)",
    cityId: 260,
  },
  {
    id: 41,
    name: "Kyimyindaing (ကြည့်မြင်တိုင်)",
    description: "Kyimyindaing (ကြည့်မြင်တိုင်)",
    cityId: 260,
  },
  {
    id: 42,
    name: "Lanmadaw (လမ်းမတော်)",
    description: "Lanmadaw (လမ်းမတော်)",
    cityId: 260,
  },
  {
    id: 43,
    name: "Latha (လသာ)",
    description: "Latha (လသာ)",
    cityId: 260,
  },
  {
    id: 44,
    name: "Mayangon (မရမ်းကုန်း)",
    description: "Mayangon (မရမ်းကုန်း)",
    cityId: 260,
  },
  {
    id: 45,
    name: "Mingala Taungnyunt (မင်္ဂလာတောင်ညွန့်)",
    description: "Mingala Taungnyunt (မင်္ဂလာတောင်ညွန့်)",
    cityId: 260,
  },
  {
    id: 46,
    name: "Mingaladon (မင်္ဂလာဒုံ)",
    description: "Mingaladon (မင်္ဂလာဒုံ)",
    cityId: 260,
  },
  {
    id: 47,
    name: "North Dagon (ဒဂုံမြို့သစ် (မြောက်ပိုင်း))",
    description: "North Dagon (ဒဂုံမြို့သစ် (မြောက်ပိုင်း))",
    cityId: 260,
  },
  {
    id: 48,
    name: "North Okkalapa (မြောက်ဥက္ကလာပ)",
    description: "North Okkalapa (မြောက်ဥက္ကလာပ)",
    cityId: 260,
  },
  {
    id: 49,
    name: "Pabedan (ပန်းဘဲတန်း)",
    description: "Pabedan (ပန်းဘဲတန်း)",
    cityId: 260,
  },
  {
    id: 50,
    name: "Pazundaung (ပုဇွန်တောင်)",
    description: "Pazundaung (ပုဇွန်တောင်)",
    cityId: 260,
  },
  {
    id: 51,
    name: "Sanchaung (စမ်းချောင်း)",
    description: "Sanchaung (စမ်းချောင်း)",
    cityId: 260,
  },
  {
    id: 52,
    name: "Seikkan (ဆိပ်ကမ်း)",
    description: "Seikkan (ဆိပ်ကမ်း)",
    cityId: 260,
  },
  {
    id: 53,
    name: "Seikkyi Kanaungto (ဆိပ်ကြီးခနောင်တို)",
    description: "Seikkyi Kanaungto (ဆိပ်ကြီးခနောင်တို)",
    cityId: 260,
  },
  {
    id: 54,
    name: "Shwepyitha (ရွှေပြည်သာ)",
    description: "Shwepyitha (ရွှေပြည်သာ)",
    cityId: 260,
  },
  {
    id: 55,
    name: "South Dagon (ဒဂုံမြို့သစ် (တောင်ပိုင်း))",
    description: "South Dagon (ဒဂုံမြို့သစ် (တောင်ပိုင်း))",
    cityId: 260,
  },
  {
    id: 56,
    name: "South Okkalapa (တောင်ဥက္ကလာပ)",
    description: "South Okkalapa (တောင်ဥက္ကလာပ)",
    cityId: 260,
  },
  {
    id: 57,
    name: "Tamwe (တာမွေ)",
    description: "Tamwe (တာမွေ)",
    cityId: 260,
  },
  {
    id: 58,
    name: "Thaketa (သာကေတ)",
    description: "Thaketa (သာကေတ)",
    cityId: 260,
  },
  {
    id: 59,
    name: "Thingangyun (သင်္ဃန်းကျွန်း)",
    description: "Thingangyun (သင်္ဃန်းကျွန်း)",
    cityId: 260,
  },
  {
    id: 60,
    name: "Yankin (ရန်ကင်း)",
    description: "Yankin (ရန်ကင်း)",
    cityId: 260,
  },
  {
    id: 356,
    name: "Kawhmu (ကော့မှူး)",
    description: "Kawhmu (ကော့မှူး)",
    cityId: 260,
  },
  {
    id: 357,
    name: "Kungyangon(ကွမ်းခြံကုန်း)",
    description: "Kungyangon(ကွမ်းခြံကုန်း)",
    cityId: 260,
  },
  {
    id: 358,
    name: "Kyauktan(ကျောက်တန်း)",
    description: "Kyauktan(ကျောက်တန်း)",
    cityId: 260,
  },
  {
    id: 359,
    name: "Thanlyin (သန်လျင်)",
    description: "Thanlyin (သန်လျင်)",
    cityId: 260,
  },
  {
    id: 360,
    name: "Thongwa (သုံးခွ)",
    description: "Thongwa (သုံးခွ)",
    cityId: 260,
  },
  {
    id: 361,
    name: "Twante (တွံတေး)",
    description: "Twante (တွံတေး)",
    cityId: 260,
  },
  {
    id: 362,
    name: "Hlegu (လှည်းကူး)",
    description: "Hlegu (လှည်းကူး)",
    cityId: 260,
  },
  {
    id: 363,
    name: "Hmawbi (မှော်ဘီ)",
    description: "Hmawbi (မှော်ဘီ)",
    cityId: 260,
  },
  {
    id: 364,
    name: "Htantabin (ထန်းတစ်ပင်)",
    description: "Htantabin (ထန်းတစ်ပင်)",
    cityId: 260,
  },
  {
    id: 365,
    name: "Taikkyi (တိုက်ကြီး)",
    description: "Taikkyi (တိုက်ကြီး)",
    cityId: 260,
  },
  {
    id: 366,
    name: "Kayan (ခရမ်း)",
    description: "Kayan (ခရမ်း)",
    cityId: 260,
  },
  {
    id: 367,
    name: "Yuzana Garden (ယုဇနဥယျာဉ်မြို့တော်)",
    description: "Yuzana Garden (ယုဇနဥယျာဉ်မြို့တော်)",
    cityId: 260,
  },
];
